Periodically check pcap stats and warn if dropping
Summary:

I suspected we might be dropping packets... but we don't seem to be.
This seems like a good check to have in place.  It would be good to
 have
some performance regressions at somepoint to validate the packets/time

 estimator here.

Test Plan:

No test!  Open to feedback but seems both hard to test and low ROI.
Wish I was a better programmer.

     Running `target\debug\desktop.exe`
 INFO  libconntrack::pcap > Starting pcap capture on \Device\NPF_{3641B7EC-1FE7-40F9-A5A6-C7BFAC9E737C}
 DEBUG libconntrack::pcap > Pcap stats check - no dropped packets
 DEBUG libconntrack::pcap > Pcap stats check - no dropped packets
 DEBUG libconntrack::pcap > Pcap stats check - no dropped packets
error: process didn't exit successfully: `target\debug\desktop.exe` (exit code: 0xc000013a, STATUS_CONTROL_C_EXIT)